NXPY-253: Restore capability to use the client with a local HTTP server
nuxeo/nuxeo-python-client pull request #300
Opened 2024-01-18 04:12 UTC by gitofanindya

2024-02-21 07:49 UTC, mr-shekhar requested changes
tests needs to be updated.

2024-02-27 07:53 UTC, swetayadav1 approved these changes

2024-02-27 07:55 UTC, mr-shekhar approved these changes
👍

2024-02-27 08:00 UTC, poojadaine approved these changes

2024-02-27 08:06 UTC, merged