NXPY-254: Authorization Error for OAuth
nuxeo/nuxeo-python-client pull request #302
Opened 2024-02-21 09:20 UTC by gitofanindya

2024-02-29 07:09 UTC, mr-shekhar requested changes
The test cases are not properly written. Pl. follow the standard practise of writing testcases, as discussed.

2024-04-02 05:42 UTC, swetayadav1 approved these changes

2024-04-02 06:15 UTC, gitofanindya commented
An SSL/TLS certificate is a digital object that allows systems to verify the identity & subsequently establish an encrypted network connection to another system using the Secure Sockets Layer/Transport Layer Security (SSL/TLS) protocol. Certificates are used within a cryptographic system known as a public key infrastructure (PKI). PKI provides a way for one party to establish the identity of another party using certificates if they both trust a third-party - known as a certificate authority. SSL/TLS certificates thus act as digital identity cards to secure network communications, establish the identity of websites over the Internet as well as resources on private networks.

A self-signed TLS/SSL certificate is not signed by a publicly trusted certificate authority (CA) but instead by the developer or company that is responsible for the website; as they are not signed by a publicly trusted CA, they are usually considered unsafe for public applications and websites.
The role of a public CA is to guarantee the validity of the information included in a certificate, especially the ownership and/or control of the domain name(s) associated with the certificate in the case of [TLS/SSL]. Therefore, using self-signed certificates is the equivalent of using credentials that have not been issued by a valid authority.

However, if a self-signed certificate needs to be used, we need to turn off the certificate verification as it is not signed by any trusted CA, the verification will fail.

This PR adds improvements to the Nuxeo Python client's OAuth2 authentication system. In particular, it introduces a new 'verify' feature that allows SSL certificates to be verified during the OAuth2 authorization process. This property ensures that SSL verification can be turned on or off as needed in a number of ways. The adjustments include setting this parameter's initial value in the class constructor, adapting the token refresh mechanism to take it, and making sure it is supplied accurately when requesting and refreshing tokens.

2024-04-02 06:36 UTC, mr-shekhar approved these changes
👍

2024-04-02 06:45 UTC, poojadaine approved these changes

2024-04-02 06:47 UTC, merged